# Generated by Django 4.2.5 on 2023-09-18 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=200)),
                ('salary', models.IntegerField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('required_experience', models.BooleanField(default=False)),
                ('request_date', models.DateField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Запрос пользователя',
                'verbose_name_plural': 'Запросы пользователей',
            },
        ),
    ]
